# Generated by Django 4.2.23 on 2026-04-26 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miro', '0003_boardaccess'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='boardaccess',
            new_name='miro_boarda_user_id_e19366_idx',
            old_name='miro_boarda_user_id_7fb95b_idx',
        ),
        migrations.RenameIndex(
            model_name='boardaccess',
            new_name='miro_boarda_project_8f57a4_idx',
            old_name='miro_boarda_project_4e7e98_idx',
        ),
    ]
