# Generated by Django 4.2.23 on 2026-05-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_approval', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetpool',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Optional label to distinguish pools with the same channel/currency', max_length=200),
        ),
    ]
