# Generated by Django 4.2.23 on 2026-05-12 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget_approval', '0005_add_cancelled_status_to_budget_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetrequest',
            name='current_approver',
            field=models.ForeignKey(blank=True, help_text='Current approver assigned to this request', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_budget_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
