# Generated by Django 4.2.23 on 2026-05-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_approval', '0006_allow_null_current_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetpool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
