# Generated by Django 4.2.23 on 2026-08-07 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_remove_non_group_pinned_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatOutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_schema', models.CharField(max_length=128)),
                ('event_type', models.CharField(choices=[('message.realtime', 'Message realtime delivery'), ('message.notifications', 'Message persisted notifications')], max_length=64)),
                ('aggregate_id', models.PositiveBigIntegerField(help_text='Tenant Message primary key')),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('claimed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['published_at', 'available_at', 'claimed_at'], name='chat_outbox_pending_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='chatoutboxevent',
            constraint=models.UniqueConstraint(fields=('tenant_schema', 'event_type', 'aggregate_id'), name='chat_outbox_tenant_event_message_uniq'),
        ),
    ]
