# Generated by Django 4.2.23 on 2026-08-18 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0015_linkpreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='link_preview_hidden_by',
            field=models.ManyToManyField(blank=True, help_text="Users who dismissed this message's link preview card. Personal view preference: the message and the shared LinkPreview cache are untouched.", related_name='hidden_link_previews', to=settings.AUTH_USER_MODEL),
        ),
    ]
