# Generated by Django 4.2.23 on 2026-04-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_merge_meeting_heads'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingactionitem',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ActionItem',
        ),
    ]
