# Generated by Django 4.2.23 on 2026-04-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_add_is_resolved_to_meetingactionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='layout_config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
