# Generated by Django 4.2.23 on 2026-05-12 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('CLOSED', 'Closed'), ('TIMEOUT', 'Timeout'), ('INTERRUPTED', 'Interrupted')], max_length=20, null=True)),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('event_type', models.CharField(choices=[('TASK_OPEN', 'Task Open'), ('FIRST_INTERACTION', 'First Interaction'), ('IDLE_START', 'Idle Start'), ('IDLE_END', 'Idle End')], max_length=30)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('project_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('client_event_id', models.UUIDField()),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracking.trackingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'occurred_at'], name='tracking_tr_user_id_de5b2c_idx'), models.Index(fields=['content_type', 'object_id'], name='tracking_tr_content_e94f57_idx'), models.Index(fields=['project_id', 'occurred_at'], name='tracking_tr_project_a56b04_idx'), models.Index(fields=['session', 'occurred_at'], name='tracking_tr_session_bd4555_idx')],
                'unique_together': {('user', 'client_event_id')},
            },
        ),
    ]
