# Generated by Django 4.2.23 on 2026-07-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0017_supportchannel_ticket_confirmation_message'),
        ('csm', '0019_merge_20260709_2328'),
    ]

    operations = [
    ]
