# Generated by Django 4.2.23 on 2026-07-25 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_dataexportrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csm', '0026_alter_slapolicy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('trigger_event', models.CharField(choices=[('ticket_created', 'Ticket Created'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('sla_breached', 'SLA Breached'), ('customer_replied', 'Customer Replied'), ('tag_added', 'Tag Added')], max_length=30)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_automation_rules', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='core.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AutomationExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('rule_name', models.CharField(max_length=200)),
                ('trigger_event', models.CharField(max_length=30)),
                ('ticket_ref', models.PositiveIntegerField(blank=True, null=True)),
                ('actions_performed', models.JSONField(default=list)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='csm.automationrule')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_logs', to='csm.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
