# Generated by Django 4.2.23 on 2026-07-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0027_ticket_tags_automationrule_automationexecutionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csmnotification',
            name='notification_type',
            field=models.CharField(choices=[('org_invitation', 'Organisation Invitation'), ('sla_breach', 'SLA Breach'), ('automation', 'Automation Rule')], max_length=30),
        ),
    ]
