# Generated by Django 4.2.23 on 2026-08-03 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_dataexportrequest'),
        ('access_control', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOverrideAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('override_type', models.CharField(choices=[('SUPERUSER', 'Superuser'), ('ORG_ADMIN', 'Organization Admin')], max_length=16)),
                ('module', models.CharField(blank=True, help_text='Module key parsed from the request path, e.g. ASSET.', max_length=32, null=True)),
                ('action', models.CharField(blank=True, help_text='Action key mapped from the HTTP method, e.g. EDIT.', max_length=32, null=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('reason', models.TextField(blank=True, default='', help_text='Admin-provided justification for the override.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization context for the override, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_override_audits', to='core.organization')),
                ('user', models.ForeignKey(help_text='The superuser or org admin who bypassed the normal permission check.', on_delete=django.db.models.deletion.CASCADE, related_name='admin_override_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='access_cont_created_dfef44_idx'), models.Index(fields=['user', '-created_at'], name='access_cont_user_id_3b8e73_idx')],
            },
        ),
    ]
