# Generated by Django 4.2.23 on 2026-04-23 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_user_id', models.CharField(db_index=True, max_length=64)),
                ('fb_user_name', models.CharField(blank=True, default='', max_length=255)),
                ('fb_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('business_id', models.CharField(blank=True, default='', max_length=64)),
                ('business_name', models.CharField(blank=True, default='', max_length=255)),
                ('encrypted_access_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'facebook_connections',
            },
        ),
        migrations.CreateModel(
            name='MetaAdAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_account_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('timezone_name', models.CharField(blank=True, default='', max_length=64)),
                ('account_status', models.IntegerField(blank=True, null=True)),
                ('business_id', models.CharField(blank=True, default='', max_length=64)),
                ('is_owned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_accounts', to='facebook_integration.facebookconnection')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_meta_accounts', to='core.project')),
            ],
            options={
                'db_table': 'meta_ad_accounts',
                'unique_together': {('connection', 'meta_account_id')},
            },
        ),
    ]
