# Generated by Django 4.2.23 on 2026-04-19 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("calendars", "0003_calendarevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleCalendarConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "google_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("encrypted_access_token", models.TextField(blank=True, null=True)),
                ("encrypted_refresh_token", models.TextField(blank=True, null=True)),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("needs_reconnect", models.BooleanField(default=False)),
                ("last_error_message", models.TextField(blank=True, null=True)),
                (
                    "primary_calendar_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_import_at", models.DateTimeField(blank=True, null=True)),
                ("last_export_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "import_calendar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="google_calendar_import_connections",
                        to="calendars.calendar",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_calendar_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "google_calendar_connections",
            },
        ),
    ]
