# Generated by Django 4.2.23 on 2026-04-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0005_decision_planned_decision_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionstatetransition',
            name='from_status',
            field=models.CharField(choices=[('PREDRAFT', 'Pre-Draft'), ('DRAFT', 'Draft'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('COMMITTED', 'Committed'), ('REVIEWED', 'Reviewed'), ('ARCHIVED', 'Archived')], max_length=20),
        ),
        migrations.AlterField(
            model_name='decisionstatetransition',
            name='to_status',
            field=models.CharField(choices=[('PREDRAFT', 'Pre-Draft'), ('DRAFT', 'Draft'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('COMMITTED', 'Committed'), ('REVIEWED', 'Reviewed'), ('ARCHIVED', 'Archived')], max_length=20),
        ),
    ]
