# Generated by Django 4.2.23 on 2026-04-26 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('agent', '0011_insert_generate_criteria_step'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='importeddatafield',
            name='unique_imported_data_field_position',
        ),
        migrations.RemoveConstraint(
            model_name='importeddatarecord',
            name='unique_imported_data_record_row',
        ),
        migrations.RenameIndex(
            model_name='dataschematemplate',
            new_name='agent_datas_source__33cb46_idx',
            old_name='agent_dst_platform_sys_idx',
        ),
        migrations.RenameIndex(
            model_name='dataschematemplate',
            new_name='agent_datas_project_61ac9f_idx',
            old_name='agent_dst_project_sys_idx',
        ),
        migrations.RenameIndex(
            model_name='fieldcategory',
            new_name='agent_field_name_469f79_idx',
            old_name='agent_fieldcat_name_sys_idx',
        ),
        migrations.RenameIndex(
            model_name='importeddatafield',
            new_name='agent_impor_file_id_389ceb_idx',
            old_name='agent_idf_file_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='importeddatafield',
            new_name='agent_impor_file_id_448956_idx',
            old_name='agent_idf_file_canon_idx',
        ),
        migrations.RenameIndex(
            model_name='importeddatarecord',
            new_name='agent_impor_file_id_9e1224_idx',
            old_name='agent_idr_file_row_idx',
        ),
        migrations.RenameIndex(
            model_name='importeddatarecord',
            new_name='agent_impor_file_id_6d3788_idx',
            old_name='agent_idr_file_quality_idx',
        ),
        migrations.AlterField(
            model_name='agentmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('analysis', 'Analysis'), ('decision_draft', 'Decision Draft'), ('task_created', 'Task Created'), ('confirmation_request', 'Confirmation Request'), ('follow_up_prompt', 'Follow-up Prompt'), ('error', 'Error')], default='text', max_length=30),
        ),
        migrations.AlterField(
            model_name='agentworkflowstep',
            name='step_type',
            field=models.CharField(choices=[('analyze_data', 'Analyze Data'), ('call_dify', 'Call LLM (Legacy)'), ('call_llm', 'Call LLM'), ('create_decision', 'Create Decision'), ('create_tasks', 'Create Tasks'), ('generate_miro_snapshot', 'Generate Miro Snapshot'), ('create_miro_board', 'Create Miro Board'), ('custom_api', 'Custom API'), ('await_confirmation', 'Await Confirmation'), ('detect_columns', 'Detect Columns'), ('normalize_data', 'Normalize Data'), ('generate_criteria', 'Generate Criteria')], max_length=30),
        ),
        migrations.AlterField(
            model_name='dataschematemplate',
            name='column_definitions',
            field=models.JSONField(default=list, help_text='List of column spec objects (canonical_name, aliases, category, value_type, description)'),
        ),
        migrations.AlterField(
            model_name='dataschematemplate',
            name='match_threshold',
            field=models.FloatField(default=0.5, help_text='Minimum fraction of file columns that must match for this template to be applied'),
        ),
        migrations.AlterField(
            model_name='dataschematemplate',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Null = global template; set = private to this project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schema_templates', to='core.project'),
        ),
        migrations.AlterField(
            model_name='dataschematemplate',
            name='usage_count',
            field=models.IntegerField(default=0, help_text='Number of uploaded files matched against this template — used for ranking'),
        ),
        migrations.AlterField(
            model_name='importeddatafield',
            name='category',
            field=models.CharField(default='unknown', help_text='Semantic category key (references FieldCategory.name). Stored as a plain string so user-defined categories work without a FK constraint.', max_length=50),
        ),
        migrations.AlterField(
            model_name='importeddatafield',
            name='matched_template',
            field=models.ForeignKey(blank=True, help_text='Schema template that identified this column, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_fields', to='agent.dataschematemplate'),
        ),
        migrations.AlterField(
            model_name='importeddatafield',
            name='max_value',
            field=models.TextField(blank=True, help_text='Maximum value as string (numeric columns)', null=True),
        ),
        migrations.AlterField(
            model_name='importeddatafield',
            name='min_value',
            field=models.TextField(blank=True, help_text='Minimum value as string (numeric columns)', null=True),
        ),
        migrations.AlterField(
            model_name='importeddatafield',
            name='sample_values',
            field=models.JSONField(default=list, help_text='Up to 5 representative non-null values, for UI display and LLM context'),
        ),
        migrations.AlterField(
            model_name='importeddatarecord',
            name='quality_score',
            field=models.FloatField(default=1.0, help_text='Fraction of confirmed (non-unknown) fields with non-null values; 0.0-1.0'),
        ),
        migrations.AlterUniqueTogether(
            name='importeddatafield',
            unique_together={('file', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='importeddatarecord',
            unique_together={('file', 'row_index')},
        ),
    ]
