from django.urls import path

from .views import (
    MetaAdExportCsvView,
    MetaAdExportToSpreadsheetView,
    MetaAdInsightTimeseriesView,
    MetaAdListView,
    MetaAdPerformanceView,
    MetaAdSetDetailView,
    MetaAdSetInsightTimeseriesView,
    MetaAdSetPerformanceView,
    MetaAdTriggerDailySyncAllView,
    MetaCampaignDetailView,
    MetaCampaignExportToSpreadsheetView,
    MetaCampaignInsightTimeseriesView,
    MetaCampaignListView,
    MetaCampaignPerformanceCsvExportView,
    MetaCampaignPerformanceView,
    MetaCreativeDetailView,
    MetaCreativeExportToSpreadsheetView,
    MetaCreativeInsightTimeseriesView,
    MetaCreativePerformanceCsvExportView,
    MetaCreativePerformanceView,
    MetaCreativeVideoSourceView,
    MetaInsightListView,
    MetaSummaryView,
    MetaSyncRunListView,
    MetaSyncRunTriggerView,
)


urlpatterns = [
    path(
        "ad_accounts/<int:ad_account_id>/campaigns/",
        MetaCampaignListView.as_view(),
        name="meta-campaigns",
    ),
    path(
        "ad_accounts/<int:ad_account_id>/campaign_performance/",
        MetaCampaignPerformanceView.as_view(),
        name="meta-campaign-performance",
    ),
    path(
        "ad_accounts/<int:ad_account_id>/creative_performance/",
        MetaCreativePerformanceView.as_view(),
        name="meta-creative-performance",
    ),
    path(
        "ad_accounts/<int:ad_account_id>/adset_performance/",
        MetaAdSetPerformanceView.as_view(),
        name="meta-adset-performance",
    ),
    path(
        "ad_accounts/<int:ad_account_id>/ad_performance/",
        MetaAdPerformanceView.as_view(),
        name="meta-ad-performance",
    ),
    path(
        "ad_accounts/<int:ad_account_id>/ad_performance/export.csv/",
        MetaAdExportCsvView.as_view(),
        name="meta-ad-performance-export-csv",
    ),
    path(
        "ad_accounts/<int:ad_account_id>/ad_performance/export.spreadsheet/",
        MetaAdExportToSpreadsheetView.as_view(),
        name="meta-ad-performance-export-spreadsheet",
    ),
    path(
        "ad_accounts/<int:ad_account_id>/creative_performance/export.csv/",
        MetaCreativePerformanceCsvExportView.as_view(),
        name="meta-creative-performance-export-csv",
    ),
    path(
        "ad_accounts/<int:ad_account_id>/creative_performance/export.spreadsheet/",
        MetaCreativeExportToSpreadsheetView.as_view(),
        name="meta-creative-performance-export-spreadsheet",
    ),
    path(
        "ad_accounts/<int:ad_account_id>/campaign_performance/export.csv/",
        MetaCampaignPerformanceCsvExportView.as_view(),
        name="meta-campaign-performance-export-csv",
    ),
    path(
        "ad_accounts/<int:ad_account_id>/campaign_performance/export.spreadsheet/",
        MetaCampaignExportToSpreadsheetView.as_view(),
        name="meta-campaign-performance-export-spreadsheet",
    ),
    path(
        "ad_accounts/<int:ad_account_id>/ads/",
        MetaAdListView.as_view(),
        name="meta-ads",
    ),
    path(
        "ad_accounts/<int:ad_account_id>/ads/<int:ad_id>/insights_timeseries/",
        MetaAdInsightTimeseriesView.as_view(),
        name="meta-ad-insights-timeseries",
    ),
    path(
        "ad_accounts/<int:ad_account_id>/insights/",
        MetaInsightListView.as_view(),
        name="meta-insights",
    ),
    path(
        "ad_accounts/<int:ad_account_id>/sync/",
        MetaSyncRunTriggerView.as_view(),
        name="meta-sync-trigger",
    ),
    path(
        "ad_accounts/<int:ad_account_id>/sync_runs/",
        MetaSyncRunListView.as_view(),
        name="meta-sync-runs",
    ),
    path(
        "summary/",
        MetaSummaryView.as_view(),
        name="meta-summary",
    ),
    path(
        "trigger_daily_sync_all/",
        MetaAdTriggerDailySyncAllView.as_view(),
        name="meta-trigger-daily-sync-all",
    ),
    path(
        "campaigns/<int:campaign_id>/",
        MetaCampaignDetailView.as_view(),
        name="meta-campaign-detail",
    ),
    path(
        "campaigns/<int:campaign_id>/performance_timeseries/",
        MetaCampaignInsightTimeseriesView.as_view(),
        name="meta-campaign-timeseries",
    ),
    path(
        "adsets/<int:adset_id>/",
        MetaAdSetDetailView.as_view(),
        name="meta-adset-detail",
    ),
    path(
        "adsets/<int:adset_id>/performance_timeseries/",
        MetaAdSetInsightTimeseriesView.as_view(),
        name="meta-adset-timeseries",
    ),
    path(
        "creatives/<int:creative_id>/",
        MetaCreativeDetailView.as_view(),
        name="meta-creative-detail",
    ),
    path(
        "creatives/<int:creative_id>/video_source/",
        MetaCreativeVideoSourceView.as_view(),
        name="meta-creative-video-source",
    ),
    path(
        "creatives/<int:creative_id>/performance_timeseries/",
        MetaCreativeInsightTimeseriesView.as_view(),
        name="meta-creative-timeseries",
    ),
]
