# Generated by Django 4.2.23 on 2026-04-23 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0003_initial'),
        ('facebook_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(default='hourly', max_length=32)),
                ('status', models.CharField(choices=[('running', 'Running'), ('ok', 'OK'), ('partial', 'Partial'), ('error', 'Error')], default='running', max_length=16)),
                ('level_counts', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('ad_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='facebook_integration.metaadaccount')),
            ],
            options={
                'db_table': 'meta_sync_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MetaCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('meta_campaign_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('objective', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('effective_status', models.CharField(blank=True, default='', max_length=32)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('daily_budget_cents', models.BigIntegerField(blank=True, null=True)),
                ('lifetime_budget_cents', models.BigIntegerField(blank=True, null=True)),
                ('special_ad_categories', models.JSONField(blank=True, default=list)),
                ('is_deleted_on_meta', models.BooleanField(default=False)),
                ('ad_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='facebook_integration.metaadaccount')),
                ('mediajira_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_campaigns', to='campaign.campaign')),
            ],
            options={
                'db_table': 'meta_campaigns',
            },
        ),
        migrations.CreateModel(
            name='MetaAdSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('meta_adset_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('effective_status', models.CharField(blank=True, default='', max_length=32)),
                ('billing_event', models.CharField(blank=True, default='', max_length=64)),
                ('optimization_goal', models.CharField(blank=True, default='', max_length=64)),
                ('bid_amount_cents', models.BigIntegerField(blank=True, null=True)),
                ('targeting', models.JSONField(blank=True, default=dict)),
                ('daily_budget_cents', models.BigIntegerField(blank=True, null=True)),
                ('lifetime_budget_cents', models.BigIntegerField(blank=True, null=True)),
                ('is_deleted_on_meta', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adsets', to='meta_ads.metacampaign')),
            ],
            options={
                'db_table': 'meta_adsets',
            },
        ),
        migrations.CreateModel(
            name='MetaAdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('meta_creative_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('title', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', max_length=1024)),
                ('video_id', models.CharField(blank=True, default='', max_length=64)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=1024)),
                ('object_type', models.CharField(blank=True, default='', max_length=64)),
                ('call_to_action_type', models.CharField(blank=True, default='', max_length=64)),
                ('asset_feed_spec', models.JSONField(blank=True, default=dict)),
                ('ad_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='facebook_integration.metaadaccount')),
            ],
            options={
                'db_table': 'meta_ad_creatives',
            },
        ),
        migrations.CreateModel(
            name='MetaAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('meta_ad_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('effective_status', models.CharField(blank=True, default='', max_length=32)),
                ('is_deleted_on_meta', models.BooleanField(default=False)),
                ('adset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='meta_ads.metaadset')),
                ('creative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='meta_ads.metaadcreative')),
            ],
            options={
                'db_table': 'meta_ads',
            },
        ),
        migrations.CreateModel(
            name='MetaInsightDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impressions', models.BigIntegerField(default=0)),
                ('reach', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('frequency', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('ctr', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('cpc', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cpm', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('leads', models.IntegerField(default=0)),
                ('calls', models.IntegerField(default=0)),
                ('purchases', models.IntegerField(default=0)),
                ('messages', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('video_p25', models.IntegerField(default=0)),
                ('video_p50', models.IntegerField(default=0)),
                ('video_p75', models.IntegerField(default=0)),
                ('video_p100', models.IntegerField(default=0)),
                ('video_avg_watch_seconds', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights_daily', to='meta_ads.metaad')),
            ],
            options={
                'db_table': 'meta_insight_daily',
                'indexes': [models.Index(fields=['ad', 'date'], name='meta_insigh_ad_id_6c9306_idx'), models.Index(fields=['date'], name='meta_insigh_date_106929_idx')],
                'unique_together': {('ad', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='metacampaign',
            index=models.Index(fields=['ad_account', 'effective_status'], name='meta_campai_ad_acco_03f561_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metacampaign',
            unique_together={('ad_account', 'meta_campaign_id')},
        ),
        migrations.AlterUniqueTogether(
            name='metaadset',
            unique_together={('campaign', 'meta_adset_id')},
        ),
        migrations.AlterUniqueTogether(
            name='metaadcreative',
            unique_together={('ad_account', 'meta_creative_id')},
        ),
        migrations.AddIndex(
            model_name='metaad',
            index=models.Index(fields=['adset', 'effective_status'], name='meta_ads_adset_i_214043_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metaad',
            unique_together={('adset', 'meta_ad_id')},
        ),
    ]
