# Generated by Django 4.2.23 on 2026-04-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metainsightdaily',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metainsightdaily',
            name='lpv_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metainsightdaily',
            name='video_3sec_count',
            field=models.IntegerField(default=0),
        ),
    ]
