# Generated by Django 4.2.23 on 2026-05-15 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0013_taskpin"),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='is_clarification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent comment if this is a reply', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='task.taskcomment'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='response_time_secs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CollaborationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('comment', 'Comment'), ('clarification', 'Clarification'), ('reviewer_ping', 'Reviewer Ping'), ('shared_access', 'Shared Access'), ('approval_delay', 'Approval Delay')], max_length=50)),
                ('meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_events', to='task.task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaboration_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collaboration_events',
                'indexes': [models.Index(fields=['task', 'event_type'], name='collaborati_task_id_71eda8_idx'), models.Index(fields=['created_at'], name='collaborati_created_2950c0_idx')],
            },
        ),
    ]
