# Generated by Django 4.2.23 on 2026-08-22 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0014_dataexportrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('role.created', 'Role Created'), ('role.updated', 'Role Updated'), ('role.deleted', 'Role Deleted'), ('role.permissions_updated', 'Role Permissions Updated'), ('role.permissions_copied', 'Role Permissions Copied'), ('user_role.assigned', 'User Role Assigned'), ('user_role.removed', 'User Role Removed'), ('project.updated', 'Project Updated'), ('project.deleted', 'Project Deleted'), ('project.labels_updated', 'Project Labels Updated'), ('org.slug_updated', 'Org Slug Updated'), ('org.deleted', 'Org Deleted'), ('org.admin_assigned', 'Org Admin Assigned'), ('org.admin_removed', 'Org Admin Removed')], db_index=True, max_length=64)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(max_length=64)),
                ('target_name', models.CharField(blank=True, max_length=255)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events_acted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_events', to='core.organization')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_events', to='core.project')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
