# Generated by Django 4.2.23 on 2026-08-11 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_dataexportrequest'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminauditevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_events', to='core.organization'),
        ),
        migrations.AddField(
            model_name='adminauditevent',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_events', to='core.project'),
        ),
        migrations.AlterField(
            model_name='adminauditevent',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events_acted', to=settings.AUTH_USER_MODEL),
        ),
    ]
