# Generated by Django 4.2.23 on 2026-08-11 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_dataexportrequest'),
        ('audit', '0002_adminauditevent_organization_adminauditevent_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditevent',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_events', to='core.project'),
        ),
    ]
