# Generated by Django 4.2.23 on 2026-05-11 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0009_task_linear_issue_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_focused_ms', models.BigIntegerField(default=0)),
                ('total_keystrokes', models.BigIntegerField(default=0)),
                ('total_backspaces', models.BigIntegerField(default=0)),
                ('total_tab_switches', models.IntegerField(default=0)),
                ('total_rapid_switches', models.IntegerField(default=0)),
                ('total_mouse_hesitations', models.IntegerField(default=0)),
                ('total_inactivity_pauses', models.IntegerField(default=0)),
                ('total_repeated_navigations', models.IntegerField(default=0)),
                ('total_abnormal_interruptions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to='task.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BehavioralSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_started_at', models.DateTimeField()),
                ('window_ended_at', models.DateTimeField()),
                ('focused_ms', models.IntegerField(default=0)),
                ('keystroke_count', models.IntegerField(default=0)),
                ('backspace_count', models.IntegerField(default=0)),
                ('tab_switch_count', models.IntegerField(default=0)),
                ('rapid_switch_count', models.IntegerField(default=0)),
                ('mouse_hesitation_count', models.IntegerField(default=0)),
                ('inactivity_pause_count', models.IntegerField(default=0)),
                ('repeated_navigation_count', models.IntegerField(default=0)),
                ('abnormal_interruption_count', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='behavioral_tracking.focussession')),
            ],
            options={
                'ordering': ['session_id', 'window_started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='focussession',
            index=models.Index(fields=['user', '-started_at'], name='behavioral__user_id_14218c_idx'),
        ),
        migrations.AddIndex(
            model_name='focussession',
            index=models.Index(fields=['task', '-started_at'], name='behavioral__task_id_90faab_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioralsignal',
            index=models.Index(fields=['session', 'window_started_at'], name='behavioral__session_3c9da1_idx'),
        ),
        migrations.AddConstraint(
            model_name='behavioralsignal',
            constraint=models.CheckConstraint(check=models.Q(('focused_ms__gte', 0)), name='bt_signal_focused_ms_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='behavioralsignal',
            constraint=models.CheckConstraint(check=models.Q(('keystroke_count__gte', 0)), name='bt_signal_keystroke_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='behavioralsignal',
            constraint=models.CheckConstraint(check=models.Q(('backspace_count__gte', 0)), name='bt_signal_backspace_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='behavioralsignal',
            constraint=models.CheckConstraint(check=models.Q(('tab_switch_count__gte', 0)), name='bt_signal_tabswitch_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='behavioralsignal',
            constraint=models.CheckConstraint(check=models.Q(('rapid_switch_count__gte', 0)), name='bt_signal_rapidswitch_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='behavioralsignal',
            constraint=models.CheckConstraint(check=models.Q(('mouse_hesitation_count__gte', 0)), name='bt_signal_hesitation_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='behavioralsignal',
            constraint=models.CheckConstraint(check=models.Q(('inactivity_pause_count__gte', 0)), name='bt_signal_inactivity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='behavioralsignal',
            constraint=models.CheckConstraint(check=models.Q(('repeated_navigation_count__gte', 0)), name='bt_signal_repeatnav_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='behavioralsignal',
            constraint=models.CheckConstraint(check=models.Q(('abnormal_interruption_count__gte', 0)), name='bt_signal_abnormal_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='behavioralsignal',
            constraint=models.CheckConstraint(check=models.Q(('window_ended_at__gte', models.F('window_started_at'))), name='bt_signal_window_valid'),
        ),
    ]
