# Generated by Django 4.2.23 on 2026-04-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
