# Generated by Django 4.2.23 on 2026-04-12 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("zoom_integration", "0003_zoom_meeting_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="zoommeetingdata",
            name="zoom_host_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User whose Zoom OAuth credential owns this meeting (set when linking).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="zoom_meeting_data_hosted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
