# Generated by Django 4.2.23 on 2026-05-15 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_add_user_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_groups', to='core.project')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SupportChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Display name for this channel', max_length=200)),
                ('channel_type', models.CharField(choices=[('live_chat_widget', 'Live Chat Widget'), ('contact_form', 'Contact Form'), ('email', 'Email')], help_text='Type of support channel', max_length=30)),
                ('welcome_message', models.TextField(blank=True, default='', help_text='Message shown to customers when they open the channel')),
                ('offline_fallback_message', models.TextField(blank=True, default='', help_text='Message shown when channel is outside operating hours')),
                ('routing_destination', models.CharField(blank=True, default='', help_text='Where conversations/submissions are routed (e.g. team name or queue)', max_length=200)),
                ('operating_hours', models.JSONField(blank=True, default=dict, help_text='Weekly operating hours schedule. Example: {"monday": {"open": true, "start": "09:00", "end": "17:00"}, ...}')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive channels are hidden from customers but visible in admin')),
                ('experience_groups', models.ManyToManyField(blank=True, help_text='Experience Groups this channel is assigned to', related_name='channels', to='support_channels.experiencegroup')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_channels', to='core.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
